title: Lawrence Roman A. Quizon
email: lawrence.quizon@eee.upd.edu.ph
description: ''
baseurl: ''
url: ''
twitter_username: lafquizon
github_username: lawrence-lugs
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
